baseurl: '/'
permalink: pretty
title: 'OneSevenGraphix Website'

google_analytics_id: ""

homepage:
  show_call_box: true

logo:
  mobile: "assets/img/logo/logomark.svg"
  desktop: "assets/img/logo/logomark.svg"
  desktop_height: "36px"

footer:
  copyright_text: '&copy; <script>document.write(new Date().getFullYear())</script> OneSevenGraphix. All Rights Reserved. Developed with <i class="fa-solid fa-heart"></i> by <a href="/team"> Test.</a>'

seo:
  meta_og_title: "OneSevenGraphix Website"
  meta_og_type: "website"
  meta_og_url: "https://onesevengraphix.github.io"
  meta_og_image: "/assets/img/logo/logomark.png"
  meta_og_description: "OneSevenGraphix Website"
  meta_twitter_card: "summary"
  meta_twitter_site: "@onesevengraphix"
  meta_twitter_creator: "@onesevengraphix"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md